### ISSUE TITLE
add live reloading of generated site

### ISSUE THREAD

**Issue by markbirbeck** [markbirbeck/enginehou.se#12]
## Description

Whilst writing posts it would be good to be able to preview them. One option is to create a simple server that uses [livereload](https://www.npmjs.com/package/livereload).

## ✅  Tasks

- [x] add livereload module
- [x] add livereload script tag to HTML output
- [x] add livereload command to the makefile

## 🏁  Acceptance Criteria

- the index page can be previewed and will refresh in the browser when build is run
