### ISSUE TITLE
add Netlify deployment steps

### ISSUE THREAD

**Issue by markbirbeck** [markbirbeck/enginehou.se#3]
## Description

To publish the site we can use Netlify. This will involve placing generated HTML into a directory that Netlify can publish from.

## ✅  Tasks

- [x] add output directory and hide from Git
- [x] add NPM build instruction to create HTML output
- [x] check Netlify config to publish

## 🏁  Acceptance Criteria

- the example page is published to a Netlfy site
